# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/pc_emulator/proto/mem_access.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/pc_emulator/proto/mem_access.proto',
  package='mem_access',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n&src/pc_emulator/proto/mem_access.proto\x12\nmem_access\"\x9d\x01\n\x0bSensorInput\x12\x0e\n\x06PLC_ID\x18\x01 \x02(\t\x12\x14\n\x0cResourceName\x18\x02 \x02(\t\x12\x0f\n\x07MemType\x18\x03 \x02(\x03\x12\x12\n\nByteOffset\x18\x04 \x02(\x03\x12\x11\n\tBitOffset\x18\x05 \x02(\x03\x12\x1c\n\x14VariableDataTypeName\x18\x06 \x02(\t\x12\x12\n\nValueToSet\x18\x07 \x02(\t\"\x8c\x01\n\x0e\x41\x63tuatorOutput\x12\x0e\n\x06PLC_ID\x18\x01 \x02(\t\x12\x14\n\x0cResourceName\x18\x02 \x02(\t\x12\x0f\n\x07MemType\x18\x03 \x02(\x03\x12\x12\n\nByteOffset\x18\x04 \x02(\x03\x12\x11\n\tBitOffset\x18\x05 \x02(\x03\x12\x1c\n\x14VariableDataTypeName\x18\x06 \x02(\t\"\x18\n\x06Status\x12\x0e\n\x06status\x18\x01 \x02(\t\"\'\n\x06Result\x12\r\n\x05value\x18\x01 \x02(\t\x12\x0e\n\x06status\x18\x02 \x02(\t2\x97\x01\n\rAccessService\x12?\n\x0eSetSensorInput\x12\x17.mem_access.SensorInput\x1a\x12.mem_access.Status\"\x00\x12\x45\n\x11GetActuatorOutput\x12\x1a.mem_access.ActuatorOutput\x1a\x12.mem_access.Result\"\x00')
)




_SENSORINPUT = _descriptor.Descriptor(
  name='SensorInput',
  full_name='mem_access.SensorInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PLC_ID', full_name='mem_access.SensorInput.PLC_ID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ResourceName', full_name='mem_access.SensorInput.ResourceName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MemType', full_name='mem_access.SensorInput.MemType', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ByteOffset', full_name='mem_access.SensorInput.ByteOffset', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='BitOffset', full_name='mem_access.SensorInput.BitOffset', index=4,
      number=5, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='VariableDataTypeName', full_name='mem_access.SensorInput.VariableDataTypeName', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ValueToSet', full_name='mem_access.SensorInput.ValueToSet', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=212,
)


_ACTUATOROUTPUT = _descriptor.Descriptor(
  name='ActuatorOutput',
  full_name='mem_access.ActuatorOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PLC_ID', full_name='mem_access.ActuatorOutput.PLC_ID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ResourceName', full_name='mem_access.ActuatorOutput.ResourceName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MemType', full_name='mem_access.ActuatorOutput.MemType', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ByteOffset', full_name='mem_access.ActuatorOutput.ByteOffset', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='BitOffset', full_name='mem_access.ActuatorOutput.BitOffset', index=4,
      number=5, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='VariableDataTypeName', full_name='mem_access.ActuatorOutput.VariableDataTypeName', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=355,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='mem_access.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='mem_access.Status.status', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=357,
  serialized_end=381,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='mem_access.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='mem_access.Result.value', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='mem_access.Result.status', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=422,
)

DESCRIPTOR.message_types_by_name['SensorInput'] = _SENSORINPUT
DESCRIPTOR.message_types_by_name['ActuatorOutput'] = _ACTUATOROUTPUT
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorInput = _reflection.GeneratedProtocolMessageType('SensorInput', (_message.Message,), dict(
  DESCRIPTOR = _SENSORINPUT,
  __module__ = 'src.pc_emulator.proto.mem_access_pb2'
  # @@protoc_insertion_point(class_scope:mem_access.SensorInput)
  ))
_sym_db.RegisterMessage(SensorInput)

ActuatorOutput = _reflection.GeneratedProtocolMessageType('ActuatorOutput', (_message.Message,), dict(
  DESCRIPTOR = _ACTUATOROUTPUT,
  __module__ = 'src.pc_emulator.proto.mem_access_pb2'
  # @@protoc_insertion_point(class_scope:mem_access.ActuatorOutput)
  ))
_sym_db.RegisterMessage(ActuatorOutput)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'src.pc_emulator.proto.mem_access_pb2'
  # @@protoc_insertion_point(class_scope:mem_access.Status)
  ))
_sym_db.RegisterMessage(Status)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'src.pc_emulator.proto.mem_access_pb2'
  # @@protoc_insertion_point(class_scope:mem_access.Result)
  ))
_sym_db.RegisterMessage(Result)



_ACCESSSERVICE = _descriptor.ServiceDescriptor(
  name='AccessService',
  full_name='mem_access.AccessService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=425,
  serialized_end=576,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetSensorInput',
    full_name='mem_access.AccessService.SetSensorInput',
    index=0,
    containing_service=None,
    input_type=_SENSORINPUT,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetActuatorOutput',
    full_name='mem_access.AccessService.GetActuatorOutput',
    index=1,
    containing_service=None,
    input_type=_ACTUATOROUTPUT,
    output_type=_RESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ACCESSSERVICE)

DESCRIPTOR.services_by_name['AccessService'] = _ACCESSSERVICE

# @@protoc_insertion_point(module_scope)
